[buildPlans.IosevkadotG]
family = "IosevkadotG"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkadotG.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "unilateral-inward-serifed"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-inward-serifed-hooked"
capital-h = "serifless"
capital-i = "serifless"
capital-j = "descending-serifless"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "asymmetric-serifless"
capital-p = "open-serifless"
capital-q = "open-swash"
capital-r = "curly-open-serifless"
capital-s = "bilateral-inward-serifed"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless-with-crossbar"
a = "double-storey-toothless-rounded"
b = "toothless-rounded-serifless"
c = "unilateral-inward-serifed"
d = "toothless-rounded-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "single-storey-earless-rounded"
h = "straight-serifless"
i = "tailed-serifed"
j = "serifed"
k = "cursive-serifless"
l = "tailed-serifed"
m = "earless-single-arch-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
s = "bilateral-inward-serifed"
t = "bent-hook-asymmetric"
u = "toothless-rounded-serifless"
v = "cursive-serifless"
w = "cursive-serifless"
x = "chancery"
y = "cursive-serifless"
z = "curly-serifless-with-crossbar"
capital-eszet = "flat-top-serifless"
long-s = "bent-hook-diagonal-tailed"
eszet = "longs-s-lig-tailed-serifless"
lower-eth = "curly-bar"
capital-thorn = "serifless"
lower-thorn = "serifless"
lower-alpha = "crossing"
capital-gamma = "serifless"
capital-delta = "curly"
lower-delta = "flat-top"
lower-iota = "serifed-diagonal-tailed"
capital-lambda = "curly-serifless"
lower-lambda = "curly-tailed-turn"
lower-mu = "toothless-rounded-serifless"
lower-xi = "rounded"
lower-pi = "small-capital"
lower-tau = "tailed"
lower-chi = "chancery"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ze = "bilateral-inward-serifed"
cyrl-ze = "bilateral-inward-serifed"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ka = "symmetric-connected-serifless"
cyrl-el = "tailed"
cyrl-em = "slanted-sides-hanging-serifless"
cyrl-en = "serifless"
cyrl-er = "earless-rounded-serifless"
cyrl-capital-u = "curly-serifless"
cyrl-u = "curly-serifless"
cyrl-ef = "split-cursive"
cyrl-che = "tailed"
cyrl-yeri = "cursive"
cyrl-yery = "round"
cyrl-capital-e = "bilateral-inward-serifed"
cyrl-e = "bilateral-inward-serifed"
cyrl-capital-ya = "straight-open-serifless"
cyrl-ya = "straight-open-serifless"
zero = "oval-dotted"
one = "no-base-long-top-serif"
two = "curly-neck-serifless"
three = "two-arcs"
four = "open-non-crossing-serifless"
five = "oblique-flat-serifless"
six = "open-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "turn-penta-low"
underscore = "low"
caret = "low"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "large-contour"
brace = "curly-flat-boundary"
guillemet = "curly"
number-sign = "slanted-open-tall"
ampersand = "et-tailed"
at = "fourfold-solid-inner-tall"
dollar = "interrupted"
cent = "bar-interrupted-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
question = "smooth"
pilcrow = "low"
partial-derivative = "curly-bar"
micro-sign = "toothless-rounded-serifless"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted-dotted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

  [buildPlans.IosevkadotG.ligations]
  inherits = "dlig"